modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${gtlcore_compat_mod_id}"
version="${mod_version}"
displayName="${gtlcore_compat_mod_name}"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${gtlcore_compat_description}'''

[[mixins]]
config="wcwt_gtlcore_compat.mixins.json"

[[dependencies.${gtlcore_compat_mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${gtlcore_compat_mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${gtlcore_compat_mod_id}]]
modId="${wcwt_mod_id}"
mandatory=true
versionRange="[${wcwt_version},)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${gtlcore_compat_mod_id}]]
modId="gtlcore"
mandatory=true
versionRange="[1.2.3.0,)"
ordering="AFTER"
side="CLIENT"
